version: '3.7'

services:
  mongodb:
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db
  
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://admin:admin@mongodb:27017/
      - CELERY_BROKER_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis

  redis:
    image: redis:7.0-alpine
    command: redis-server
    ports:
      - "6379:6379"

  celery_worker:
    restart: always
    build: .
    command: celery -A analytus worker --loglevel=INFO
    volumes:
      - .:/code
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://admin:admin@mongodb:27017/
      - CELERY_BROKER_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis
      - web

